/**
 * INC-4417 fixture dataset.
 *
 * Everything the app knows lives here. It is generated by code, but it is
 * *deterministic* code: no Math.random, no Date.now. The same minute always
 * produces the same value, so a tool call made during the demo returns exactly
 * what it returned during development.
 *
 * The jitter below is a hash-based pseudo-noise function, not randomness. It
 * exists so the series look like telemetry instead of step functions; the
 * signal the agent has to find is in the *shape*, not in the noise.
 *
 * Ground truth, for the reader: checkout-service v2.14 (deployed 14:12) cut the
 * HikariCP connection pool from 50 to 10. Threads start queueing for a
 * connection at 14:20 under normal traffic. p99 explodes, p50 barely moves
 * (queueing, not compute), traces pool at `db.connection.acquire`, and the pool
 * logs the timeout. Rolling back dep-1104 fixes it.
 */

export type ServiceId =
  | 'checkout-service'
  | 'payment-gateway'
  | 'inventory-service'
  | 'user-service'
  | 'notification-service';

export type MetricName = 'p50' | 'p99' | 'error_rate';
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export const SERVICE_IDS: ServiceId[] = [
  'checkout-service',
  'payment-gateway',
  'inventory-service',
  'user-service',
  'notification-service',
];

/** One-minute resolution. Index 0 === 13:30, index 90 === 15:00. */
export const INCIDENT_DATE = '2026-09-03';
export const T0_ISO = `${INCIDENT_DATE}T13:30:00Z`;
/** "Now" while the incident is live: 15:00. */
export const LIVE_MINUTES = 90;
/** The fixture also holds 20 minutes of post-rollback data, revealed on approval. */
export const TOTAL_MINUTES = 110;

const T0_MS = Date.parse(T0_ISO);

export const isoAtMinute = (i: number): string => new Date(T0_MS + i * 60_000).toISOString();

export const minuteOfIso = (iso: string): number => Math.round((Date.parse(iso) - T0_MS) / 60_000);

/** "2026-09-03T14:20:00.000Z" -> "14:20" */
export const clock = (iso: string): string => iso.slice(11, 16);

// ---------------------------------------------------------------------------
// Deterministic pseudo-noise
// ---------------------------------------------------------------------------

/** Stable hash -> [0, 1). Same inputs, same output, forever. */
function hash01(a: number, b: number): number {
  const x = Math.sin(a * 127.1 + b * 311.7) * 43758.5453123;
  return x - Math.floor(x);
}

/** Stable noise in [-amp, +amp]. */
function wobble(i: number, seed: number, amp: number): number {
  return (hash01(i, seed) * 2 - 1) * amp;
}

/** Deterministic lowercase hex id of `len` chars. */
function hexId(seed: number, len: number): string {
  let out = '';
  for (let k = 0; out.length < len; k++) {
    out += Math.floor(hash01(seed + k * 7.13, 91.7) * 0xffff)
      .toString(16)
      .padStart(4, '0');
  }
  return out.slice(0, len);
}

const round = (v: number, dp = 1): number => {
  const f = 10 ** dp;
  return Math.round(v * f) / f;
};

/** 0 -> 0, 1 -> 1, decelerating. Used for the latency ramp. */
const easeOut = (p: number) => 1 - (1 - p) * (1 - p);

/** Linear ramp from `from` to `to` across [start, start + span] minutes. */
function ramp(i: number, start: number, span: number, from: number, to: number): number {
  if (i <= start) return from;
  if (i >= start + span) return to;
  return from + (to - from) * easeOut((i - start) / span);
}

// ---------------------------------------------------------------------------
// Key moments
// ---------------------------------------------------------------------------

/** Anomaly onset on checkout-service. 14:20. */
export const ANOMALY_START_MINUTE = 50;
/** checkout-service v2.14 ships. 14:12. */
export const ROOT_CAUSE_DEPLOY_MINUTE = 42;
/** Where the rollback lands in the post-mitigation series. 15:03. */
export const ROLLBACK_MINUTE = 93;

// ---------------------------------------------------------------------------
// Metric series
// ---------------------------------------------------------------------------

export interface MetricPoint {
  /** ISO timestamp, minute resolution. */
  t: string;
  v: number;
}

/**
 * p50/p99 are computed over *successful* responses; requests that exhaust the
 * 30s connection timeout are counted in error_rate, not in the latency
 * histogram. That is why p99 plateaus at ~3.4s rather than at the timeout.
 */
function seriesValue(service: ServiceId, metric: MetricName, i: number): number {
  switch (service) {
    case 'checkout-service': {
      // Post-rollback recovery only exists past the live edge.
      const recovering = i >= ROLLBACK_MINUTE;
      if (metric === 'p99') {
        if (recovering) return round(ramp(i, ROLLBACK_MINUTE, 5, 3400, 184) + wobble(i, 3, 12), 1);
        return round(ramp(i, ANOMALY_START_MINUTE - 1, 5, 181, 3400) + wobble(i, 3, i < ANOMALY_START_MINUTE ? 14 : 110), 1);
      }
      if (metric === 'p50') {
        if (recovering) return round(ramp(i, ROLLBACK_MINUTE, 5, 78, 62) + wobble(i, 5, 3), 1);
        return round(ramp(i, ANOMALY_START_MINUTE - 1, 5, 62, 78) + wobble(i, 5, 4), 1);
      }
      if (recovering) return round(Math.max(0.02, ramp(i, ROLLBACK_MINUTE, 4, 4.2, 0.11) + wobble(i, 7, 0.05)), 2);
      return round(
        Math.max(0.02, ramp(i, ANOMALY_START_MINUTE - 1, 7, 0.1, 4.2) + wobble(i, 7, i < ANOMALY_START_MINUTE ? 0.04 : 0.18)),
        2,
      );
    }

    case 'payment-gateway': {
      // Downstream victim: checkout holds payment sessions open longer.
      const recovering = i >= ROLLBACK_MINUTE;
      const onset = ANOMALY_START_MINUTE + 2;
      if (metric === 'p99') {
        if (recovering) return round(ramp(i, ROLLBACK_MINUTE, 5, 520, 243) + wobble(i, 11, 16), 1);
        return round(ramp(i, onset, 6, 241, 520) + wobble(i, 11, i < onset ? 18 : 30), 1);
      }
      if (metric === 'p50') {
        if (recovering) return round(ramp(i, ROLLBACK_MINUTE, 5, 104, 88) + wobble(i, 13, 4), 1);
        return round(ramp(i, onset, 6, 88, 104) + wobble(i, 13, 5), 1);
      }
      if (recovering) return round(Math.max(0.02, ramp(i, ROLLBACK_MINUTE, 4, 0.9, 0.21) + wobble(i, 17, 0.05)), 2);
      return round(Math.max(0.02, ramp(i, onset + 2, 5, 0.2, 0.9) + wobble(i, 17, 0.06)), 2);
    }

    case 'inventory-service': {
      // Red herring: a cache-TTL deploy at 13:44 causes a bump that self-resolves.
      const bump = (peak: number, base: number) => {
        if (i < 15 || i > 24) return base;
        const up = ramp(i, 15, 3, base, peak);
        const down = ramp(i, 20, 4, peak, base);
        return i <= 19 ? up : down;
      };
      if (metric === 'p99') return round(bump(431, 151) + wobble(i, 19, 12), 1);
      if (metric === 'p50') return round(bump(58, 44) + wobble(i, 23, 3), 1);
      return round(Math.max(0.02, bump(0.45, 0.1) + wobble(i, 29, 0.05)), 2);
    }

    case 'user-service': {
      if (metric === 'p99') return round(95 + wobble(i, 31, 8), 1);
      if (metric === 'p50') return round(31 + wobble(i, 37, 3), 1);
      return round(Math.max(0.01, 0.05 + wobble(i, 41, 0.03)), 2);
    }

    case 'notification-service': {
      // Chronically noisy but stable: stops "highest error rate" being a giveaway.
      if (metric === 'p99') return round(211 + wobble(i, 43, 16), 1);
      if (metric === 'p50') return round(58 + wobble(i, 47, 4), 1);
      return round(Math.max(0.05, 0.31 + wobble(i, 53, 0.08)), 2);
    }
  }
}

const buildSeries = (): Record<ServiceId, Record<MetricName, MetricPoint[]>> => {
  const out = {} as Record<ServiceId, Record<MetricName, MetricPoint[]>>;
  for (const service of SERVICE_IDS) {
    out[service] = { p50: [], p99: [], error_rate: [] };
    for (const metric of ['p50', 'p99', 'error_rate'] as MetricName[]) {
      for (let i = 0; i <= TOTAL_MINUTES; i++) {
        out[service][metric].push({ t: isoAtMinute(i), v: seriesValue(service, metric, i) });
      }
    }
  }
  return out;
};

export const SERIES = buildSeries();

export const METRIC_UNITS: Record<MetricName, string> = {
  p50: 'ms',
  p99: 'ms',
  error_rate: '%',
};

export const METRIC_LABELS: Record<MetricName, string> = {
  p50: 'p50 latency',
  p99: 'p99 latency',
  error_rate: 'error rate',
};

// ---------------------------------------------------------------------------
// Services
// ---------------------------------------------------------------------------

export interface ServiceMeta {
  id: ServiceId;
  owner: string;
  tier: 1 | 2 | 3;
  /** Steady-state requests per minute. Used to compute incident impact. */
  rpm: number;
  /** Services this one calls. Used only for human context in the left rail. */
  dependsOn: ServiceId[];
}

export const SERVICES: ServiceMeta[] = [
  { id: 'checkout-service', owner: 'team-commerce', tier: 1, rpm: 1240, dependsOn: ['payment-gateway', 'inventory-service'] },
  { id: 'payment-gateway', owner: 'team-payments', tier: 1, rpm: 980, dependsOn: [] },
  { id: 'inventory-service', owner: 'team-catalog', tier: 2, rpm: 2100, dependsOn: [] },
  { id: 'user-service', owner: 'team-identity', tier: 2, rpm: 3400, dependsOn: [] },
  { id: 'notification-service', owner: 'team-growth', tier: 3, rpm: 620, dependsOn: [] },
];

// ---------------------------------------------------------------------------
// Alerts
// ---------------------------------------------------------------------------

export interface Alert {
  id: string;
  service: ServiceId;
  name: string;
  severity: 'critical' | 'warning';
  firedAt: string;
  resolvedAt: string | null;
}

export const ALERTS: Alert[] = [
  {
    id: 'alr-8801',
    service: 'checkout-service',
    name: 'p99_latency_above_1000ms',
    severity: 'critical',
    firedAt: isoAtMinute(51),
    resolvedAt: null,
  },
  {
    id: 'alr-8802',
    service: 'checkout-service',
    name: 'error_rate_above_2pct',
    severity: 'critical',
    firedAt: isoAtMinute(53),
    resolvedAt: null,
  },
  {
    id: 'alr-8803',
    service: 'checkout-service',
    name: 'http_5xx_burst',
    severity: 'warning',
    firedAt: isoAtMinute(54),
    resolvedAt: null,
  },
  {
    id: 'alr-8804',
    service: 'payment-gateway',
    name: 'p99_latency_above_400ms',
    severity: 'warning',
    firedAt: isoAtMinute(56),
    resolvedAt: null,
  },
  {
    id: 'alr-8790',
    service: 'inventory-service',
    name: 'p99_latency_above_300ms',
    severity: 'warning',
    firedAt: isoAtMinute(17),
    resolvedAt: isoAtMinute(24),
  },
];

// ---------------------------------------------------------------------------
// Deploys
// ---------------------------------------------------------------------------

export interface Deploy {
  id: string;
  service: ServiceId;
  version: string;
  at: string;
  author: string;
  /** Human-readable summary of what changed. */
  changes: string[];
  /** The line that matters. Written the way a real deploy annotation reads. */
  diffNote: string;
}

export const DEPLOYS: Deploy[] = [
  {
    id: 'dep-1091',
    service: 'inventory-service',
    version: 'v1.9',
    at: isoAtMinute(14), // 13:44
    author: 'team-catalog',
    changes: ['Raise stock-lookup cache TTL 30s -> 300s', 'Drop unused /v1/stock/legacy route'],
    diffNote: 'config/cache.yml: stockTtlSeconds 30 -> 300. Cold-cache window expected on rollout.',
  },
  {
    id: 'dep-1104',
    service: 'checkout-service',
    version: 'v2.14',
    at: isoAtMinute(42), // 14:12
    author: 'team-commerce',
    changes: [
      'Move datasource config from env vars to config/datasource.yml',
      'Add idempotency key to order insert',
      'Tune HikariCP pool sizing',
    ],
    diffNote:
      'config/datasource.yml: hikari.maximumPoolSize 50 -> 10 (copied from the staging profile). ' +
      'hikari.connectionTimeout left at 30000ms.',
  },
  {
    id: 'dep-1112',
    service: 'user-service',
    version: 'v3.2',
    at: isoAtMinute(85), // 14:55
    author: 'team-identity',
    changes: ['Add GET /v2/profile', 'Bump jackson 2.17.1 -> 2.17.2'],
    diffNote: 'Additive endpoint. No datasource or pool changes.',
  },
];

// ---------------------------------------------------------------------------
// Traces
// ---------------------------------------------------------------------------

export interface Span {
  name: string;
  durationMs: number;
  /** Set when the span is a call into another service. */
  peer?: ServiceId;
}

export interface Trace {
  id: string;
  service: ServiceId;
  operation: string;
  t: string;
  durationMs: number;
  status: 'ok' | 'error';
  /** Non-overlapping child spans. durationMs === sum(spans) + root overhead. */
  spans: Span[];
  error?: string;
}

function checkoutSpans(i: number, kind: 'pre' | 'ramp' | 'post' | 'timeout'): Span[] {
  const acquire =
    kind === 'pre'
      ? 3 + wobble(i, 61, 1.4)
      : kind === 'ramp'
        ? ramp(i, ANOMALY_START_MINUTE - 1, 5, 3, 3050) + wobble(i, 61, 90)
        : kind === 'timeout'
          ? 30000
          : 3050 + wobble(i, 61, 190);
  const payment = kind === 'pre' ? 71 + wobble(i, 67, 12) : 128 + wobble(i, 67, 21);
  return [
    { name: 'auth.verify', durationMs: round(11 + wobble(i, 59, 2), 1) },
    { name: 'db.connection.acquire', durationMs: round(Math.max(0.4, acquire), 1) },
    { name: 'db.query cart_items', durationMs: round(48 + wobble(i, 63, 8), 1) },
    { name: 'inventory.check', durationMs: round(34 + wobble(i, 65, 6), 1), peer: 'inventory-service' },
    { name: 'payment.authorize', durationMs: round(payment, 1), peer: 'payment-gateway' },
    ...(kind === 'timeout' ? [] : [{ name: 'db.query order_insert', durationMs: round(22 + wobble(i, 69, 4), 1) }]),
  ];
}

function makeTrace(
  service: ServiceId,
  operation: string,
  minute: number,
  spans: Span[],
  status: 'ok' | 'error' = 'ok',
  error?: string,
): Trace {
  const sum = spans.reduce((a, s) => a + s.durationMs, 0);
  const overhead = round(1.2 + wobble(minute, 71, 0.6), 1);
  return {
    id: `tr-${hexId(minute + spans.length * 3.7 + service.length, 12)}`,
    service,
    operation,
    t: isoAtMinute(minute),
    durationMs: round(sum + overhead, 1),
    status,
    spans,
    error,
  };
}

function buildTraces(): Trace[] {
  const out: Trace[] = [];

  const pre = [2, 6, 9, 13, 17, 21, 24, 28, 31, 35, 38, 41, 44, 46, 48];
  const rampMinutes = [50, 51, 52, 53];
  const post = [55, 57, 58, 60, 62, 63, 65, 67, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 89];
  const timeouts = [61, 71, 83];

  for (const m of pre) out.push(makeTrace('checkout-service', 'POST /api/v1/checkout', m, checkoutSpans(m, 'pre')));
  for (const m of rampMinutes) out.push(makeTrace('checkout-service', 'POST /api/v1/checkout', m, checkoutSpans(m, 'ramp')));
  for (const m of post) out.push(makeTrace('checkout-service', 'POST /api/v1/checkout', m, checkoutSpans(m, 'post')));
  for (const m of timeouts) {
    out.push(
      makeTrace(
        'checkout-service',
        'POST /api/v1/checkout',
        m,
        checkoutSpans(m, 'timeout'),
        'error',
        'SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms',
      ),
    );
  }

  for (const m of [5, 19, 33, 47, 56, 64, 73, 81, 87]) {
    const slow = m >= 52;
    out.push(
      makeTrace('payment-gateway', 'POST /v2/authorize', m, [
        { name: 'risk.score', durationMs: round(28 + wobble(m, 73, 5), 1) },
        { name: 'psp.dispatch', durationMs: round((slow ? 168 : 92) + wobble(m, 79, slow ? 24 : 11), 1) },
        { name: 'db.query auth_log', durationMs: round(19 + wobble(m, 83, 4), 1) },
      ]),
    );
  }

  for (const m of [16, 18, 20, 22, 40, 66]) {
    const cold = m >= 15 && m <= 24;
    out.push(
      makeTrace('inventory-service', 'GET /v1/stock', m, [
        { name: 'cache.lookup', durationMs: round((cold ? 4 : 2) + wobble(m, 89, 1), 1) },
        { name: 'db.query stock_levels', durationMs: round((cold ? 288 : 41) + wobble(m, 97, cold ? 22 : 6), 1) },
      ]),
    );
  }

  for (const m of [30, 59, 85]) {
    out.push(
      makeTrace('user-service', 'GET /v1/profile', m, [
        { name: 'db.query users', durationMs: round(37 + wobble(m, 101, 6), 1) },
        { name: 'serialize', durationMs: round(6 + wobble(m, 103, 1.5), 1) },
      ]),
    );
  }

  return out.sort((a, b) => a.t.localeCompare(b.t));
}

export const TRACES: Trace[] = buildTraces();

// ---------------------------------------------------------------------------
// Logs
// ---------------------------------------------------------------------------

export interface LogLine {
  id: string;
  t: string;
  service: ServiceId;
  level: LogLevel;
  message: string;
}

function buildLogs(): LogLine[] {
  const out: Omit<LogLine, 'id'>[] = [];
  const push = (minute: number, service: ServiceId, level: LogLevel, message: string) =>
    out.push({ t: isoAtMinute(minute), service, level, message });

  // --- Baseline chatter, both before and after the anomaly -----------------
  for (let m = 0; m <= LIVE_MINUTES; m += 4) {
    push(m, 'checkout-service', 'info', `Checkout completed order=ord-${hexId(m, 8)} in ${Math.round(seriesValue('checkout-service', 'p50', m))}ms`);
  }
  for (let m = 3; m <= LIVE_MINUTES; m += 8) {
    push(m, 'notification-service', 'warn', 'Retrying webhook delivery attempt=2 endpoint=https://hooks.partner.example/orders');
  }
  for (let m = 7; m <= LIVE_MINUTES; m += 12) {
    push(m, 'notification-service', 'info', `Digest batch flushed size=${180 + Math.round(hash01(m, 109) * 90)}`);
  }
  for (let m = 4; m <= LIVE_MINUTES; m += 6) {
    push(m, 'user-service', 'info', `Session refreshed subject=usr-${hexId(m + 4, 6)}`);
  }
  for (let m = 8; m <= LIVE_MINUTES; m += 7) {
    push(m, 'payment-gateway', 'info', `Authorization approved psp=stripe latency=${Math.round(seriesValue('payment-gateway', 'p50', m))}ms`);
  }
  for (let m = 5; m <= LIVE_MINUTES; m += 10) {
    push(m, 'inventory-service', 'info', `Stock lookup batch sku_count=${20 + Math.round(hash01(m, 113) * 60)}`);
  }

  // --- Red herring: inventory cold cache after dep-1091 --------------------
  push(14, 'inventory-service', 'info', 'Deployment complete: inventory-service v1.9 (dep-1091)');
  for (const m of [15, 16, 17, 18, 19, 20]) {
    push(m, 'inventory-service', 'warn', 'Stock cache miss ratio 0.71 above threshold 0.30 - warming');
  }
  push(24, 'inventory-service', 'info', 'Stock cache miss ratio 0.06 - back within threshold');

  // --- The root cause deploy ----------------------------------------------
  push(42, 'checkout-service', 'info', 'Deployment complete: checkout-service v2.14 (dep-1104)');
  push(42, 'checkout-service', 'info', 'HikariPool-1 - Starting... maximumPoolSize=10 connectionTimeout=30000');
  push(43, 'checkout-service', 'info', 'HikariPool-1 - Start completed.');

  // --- Saturation builds quietly before the alert fires --------------------
  for (const m of [46, 48]) {
    push(m, 'checkout-service', 'debug', 'HikariPool-1 - Pool stats (total=10, active=9, idle=1, waiting=0)');
  }

  // --- The tell, repeated -------------------------------------------------
  for (const m of [50, 52, 54, 56, 58, 61, 64, 66, 69, 71, 74, 77, 79, 82, 83, 86, 88, 90]) {
    push(m, 'checkout-service', 'error', 'HikariPool-1 - Connection is not available, request timed out after 30000ms');
  }
  for (const m of [51, 55, 59, 63, 67, 72, 76, 81, 85, 89]) {
    const waiting = 12 + Math.round(hash01(m, 107) * 26);
    push(m, 'checkout-service', 'warn', `HikariPool-1 - Timeout failure stats (total=10, active=10, idle=0, waiting=${waiting})`);
  }
  for (const m of [53, 60, 68, 75, 84]) {
    push(m, 'checkout-service', 'error', 'Order submission failed: SQLTransientConnectionException acquiring connection for order_insert');
  }

  // --- Downstream noise ----------------------------------------------------
  for (const m of [57, 65, 73, 80, 87]) {
    push(m, 'payment-gateway', 'warn', 'Authorization session held open beyond 2000ms by upstream checkout-service');
  }
  push(85, 'user-service', 'info', 'Deployment complete: user-service v3.2 (dep-1112)');
  push(86, 'user-service', 'info', 'Route registered: GET /v2/profile');

  return out
    .sort((a, b) => a.t.localeCompare(b.t))
    .map((l, idx) => ({ ...l, id: `log-${idx.toString().padStart(4, '0')}` }));
}

export const LOGS: LogLine[] = buildLogs();

// ---------------------------------------------------------------------------
// Post-mitigation facts, only surfaced once a human approves the rollback.
// ---------------------------------------------------------------------------

export const ROLLBACK_LOGS: LogLine[] = [
  {
    id: 'log-rb-0',
    t: isoAtMinute(ROLLBACK_MINUTE),
    service: 'checkout-service',
    level: 'info',
    message: 'Rollback started: checkout-service v2.14 -> v2.13 (dep-1104)',
  },
  {
    id: 'log-rb-1',
    t: isoAtMinute(ROLLBACK_MINUTE + 1),
    service: 'checkout-service',
    level: 'info',
    message: 'HikariPool-1 - Starting... maximumPoolSize=50 connectionTimeout=30000',
  },
  {
    id: 'log-rb-2',
    t: isoAtMinute(ROLLBACK_MINUTE + 2),
    service: 'checkout-service',
    level: 'info',
    message: 'HikariPool-1 - Pool stats (total=50, active=11, idle=39, waiting=0)',
  },
  {
    id: 'log-rb-3',
    t: isoAtMinute(ROLLBACK_MINUTE + 5),
    service: 'checkout-service',
    level: 'info',
    message: 'Checkout completed order=ord-9f31ac04 in 61ms',
  },
];

export const INCIDENT = {
  id: 'INC-4417',
  title: 'Checkout latency spike',
  declaredAt: isoAtMinute(52),
  commander: 'you (on-call, team-commerce)',
} as const;
